Add variables selection_conditions
cloudposse/terraform-aws-backup pull request #94
Opened 2024-11-11 14:43 UTC by leonardobiffi

## what

Add new variables `selection_conditions` for `aws_backup_selection`

## why

On resource `aws_backup_selection` the `condition` block allows a list of conditions that you define to assign resources to your backup plans using tags

## references

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection#condition-1

2025-05-29 11:35 UTC, leonardobiffi commented
@Gowiem @joe-niland Is there any forecast for when this could be approved?

2025-05-29 20:03 UTC, Gowiem commented
/terratest

2025-05-29 20:06 UTC, Gowiem requested changes
This looks solid, but I have one question before we move this forward. Thanks!

2025-05-29 20:06 UTC, Gowiem commented on main.tf
> +        key   = "aws:ResourceTag/${string_equals.value.key}"
Is there other key prefixes that might fit here? Does it make more sense to have this be `string_equals.value.key` here and have consumers of this module pass `aws:ResourceTag/$THEIR_KEY` so that other consumers might be able to pass `aws:OtherTypeOfKey/$IDENTIFIER`? 

If the latter makes sense... can we switch this up? Can you document the common key prefixes that users of this module might use in the description of the `selection_conditions` variable?

2025-05-30 17:14 UTC, Gowiem commented on main.tf
> +        key   = "aws:ResourceTag/${string_equals.value.key}"
If that's the case, let's ship it 👍

2025-05-30 17:14 UTC, Gowiem submitted a review, later dismissed
:shipit:

2025-05-30 17:17 UTC, Gowiem commented
@leonardobiffi there is a formatting issue. Mind running `terraform fmt` against the code, commiting, and pushing the result?

2025-06-02 20:07 UTC, Gowiem approved these changes

2025-06-03 02:39 UTC, Gowiem commented
/terratest

2025-06-05 20:33 UTC, merged